project 'iPa图片提取.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iPa图片提取' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  target 'iPa图片提取Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iPa图片提取UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
